[package]
name = "pong"
version = "0.1.0"
authors = ["Justin Adams"]
edition = "2021"

[dependencies]
bevy = { version = "0.8.1", features = ["dynamic"] }
bevy_prototype_lyon = "0.6.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3